# Linear Regression for Multiple Variables

In [2]:
import numpy as np

In [91]:
X_train = np.array([[2104, 5, 3, 45],
                    [1416, 3, 2, 40],
                    [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])


In [92]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])

In [93]:
def mean_std(X):
    m,n = X.shape
    mean = np.zeros(n)
    std = np.zeros(n)

    for j in range(n):
        mean[j] = np.mean(X[:,j])
        std[j] = np.std(X[:,j])
    
    return mean,std
mean,std = mean_std(X_train)
mean,std

(array([1457.33333333,    3.33333333,    2.        ,   40.        ]),
 array([511.96180413,   1.24721913,   0.81649658,   4.0824829 ]))

In [109]:
def Z_Score_Normalization(X):
    '''
    X_norm[j]=(X[j] - mean) / std
    X: Features X
    X_norm: Normalized Features X
    '''
    X_norm = np.zeros(X.shape)
    m,n = X.shape

    for j in range(n):
        X_norm[:,j] = (X[:,j] - mean[j]) / std[j]

    return X_norm

X_norm = Z_Score_Normalization(X_train)
y_norm = (y_train-np.mean(y_train))/np.std(y_train)
y_mean = np.mean(y_train)
y_std = np.std(y_train)
print(X_norm)
print(y_norm)
print(y_mean)
print(y_std)


[[ 1.26311506  1.33630621  1.22474487  1.22474487]
 [-0.08073519 -0.26726124  0.          0.        ]
 [-1.18237987 -1.06904497 -1.22474487 -1.22474487]]
[ 1.39101486 -0.47458154 -0.91643332]
290.0
122.21292893961751


In [103]:
def cost_function(X,y,w,b):
    '''
    X: Matrix of size (m,n) with m examples and n features
    y: Vector of size (m,) represents labels
    w: Vector of size (n,) represents weights of n features
    b: Scalar Parameter or bias term
    
    f_wb: Precditon function
    '''

    m = X.shape[0]
    cost = 0
    for i in range(m):
        f_wb = np.dot(X[i],w)+b
        cost += (f_wb-y[i])**2
    cost = cost/(2*m)
    return cost
        

In [104]:
def compute_gradient(X,y,w,b):
    '''
    Calculates the Partial derivatives w.r.t w and b
    X: Matrix of size (m,n) with m examples and n features
    y: Vector of size (m,) represents labels
    w: Vector of size (n,) represents weights of n features
    b: Scalar Parameter or bias term
    
    f_wb: Precditon function
    '''

    m,n = X.shape

    dj_dw = np.zeros((n,))
    dj_db = 0

    for i in range(m):
        cost = np.dot(X[i],w)+b - y[i]
        for j in range(n):
            dj_dw[j] = dj_dw[j] + cost*X[i,j]
        dj_db = dj_db + cost
    dj_dw = dj_dw/m
    dj_db = dj_db/m
    return dj_dw,dj_db

In [105]:
def gradient_descent(X,y,w_in,b_in,gradient_function,alpha=0.000000001,num_iter=10000):

    w = w_in
    b = b_in
    
    for i in range(num_iter):
        dj_dw,dj_db = gradient_function(X,y,w,b)
        w = w-alpha * dj_dw
        b = b-alpha * dj_db
    return w,b

In [122]:
x_test = Z_Score_Normalization(np.array([[2500,2,3,55],
                   [1100,3,2,30]]))

w_initial = np.array([5,1,2,-1])
b_initial = 0
x_test

array([[ 2.03661027, -1.06904497,  1.22474487,  3.67423461],
       [-0.69796874, -0.26726124,  0.        , -2.44948974]])

In [123]:

w,b=gradient_descent(X_norm,y_train,w_initial,b_initial,compute_gradient)
fac = std+mean
f_wb = (np.dot(x_test,w) + b)
print(f_wb[0]+mean[0])

# print(f_wb)
for i in range(x_test.shape[0]):
    print(f'HOUSE PRICE PREDICTION {i+1}:\nArea: {(x_test[i,0]*std[0]+mean[0])} sqft\nBedrooms: {x_test[i,1]*std[1]+mean[1]}\nFloors: {x_test[i,2]*std[2]+mean[2]}\nAge: {x_test[i,3]*std[3]+mean[3]} yr\n\nPrice: ${round((f_wb[i]*y_std+y_mean)*1000,2)}\n\n')

1465.231821958556
HOUSE PRICE PREDICTION 1:
Area: 2500.0 sqft
Bedrooms: 2.0
Floors: 3.0
Age: 55.0 yr

Price: $1255297.43


HOUSE PRICE PREDICTION 2:
Area: 1100.0 sqft
Bedrooms: 3.0
Floors: 2.0
Age: 30.0 yr

Price: $130091.91


